#!/usr/bin/env node
/**
 * Phase 2A acceptance test: the customer journey in docs/PHASE_2A.md
 * ("Acceptance test"), in a real browser, against a running app connected to
 * a real Supabase project. Nothing is mocked.
 *
 *   # 1. Put the project's values in .env.local (see .env.example), with
 *   #    CUSTOMER_SIGNUPS_OPEN=true, then build and start the app:
 *   npm run build && npm start
 *   # 2. In another terminal (reads .env.local too):
 *   npm run qa:portal
 *
 * Run it against a test project, or one with no real customers yet. The first
 * customer signs up through the real form. If the project can't email test
 * addresses yet (Supabase's built-in email only reaches your own team), that
 * account is confirmed through an admin-generated link instead and the run
 * says so. The second customer is always confirmed through a real email link
 * generated by the admin API, so no email is sent.
 *
 * The service-role key is used only by this script, never by the app: to
 * generate those links, to read the database directly as a second opinion,
 * and to delete both test accounts at the end (unless E2E_KEEP_USERS=true).
 *
 * Env:
 *   BASE_URL                   the app under test (default http://localhost:3000)
 *   SUPABASE_URL               the project the app is connected to
 *   SUPABASE_PUBLISHABLE_KEY   for the direct API checks, signed in as each customer
 *   SUPABASE_SERVICE_ROLE_KEY  admin key (never commit it)
 *   E2E_EMAIL_DOMAIN           domain for the throwaway addresses (default example.net)
 *   E2E_KEEP_USERS             "true" to keep the test accounts afterwards
 *   QA_BROWSER                 msedge (default) | chrome | chromium | firefox | webkit
 *   E2E_HEADED                 "true" to watch the browser
 */
import { randomUUID } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import { chromium, firefox, webkit } from "playwright-core";

const BASE = (process.env.BASE_URL ?? "http://localhost:3000").replace(/\/$/, "");
const { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, SUPABASE_SERVICE_ROLE_KEY } = process.env;
const DOMAIN = process.env.E2E_EMAIL_DOMAIN ?? "example.net";
const KEEP = process.env.E2E_KEEP_USERS === "true";
const CHANNEL = process.env.QA_BROWSER ?? "msedge";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY || !SUPABASE_SERVICE_ROLE_KEY) {
  console.error("Set SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY and SUPABASE_SERVICE_ROLE_KEY (see the comment at the top of this file).");
  process.exit(2);
}

const noSession = { auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false } };
const admin = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, noSession);

// ── Tiny test runner: steps run in order and stop at the first failure ──────
const results = [];
async function step(title, fn) {
  try {
    await fn();
    results.push({ title, ok: true });
    console.log(`  ✓ ${title}`);
  } catch (error) {
    results.push({ title, ok: false });
    console.log(`  ✗ ${title}\n      ${String(error?.message ?? error).split("\n")[0]}`);
    throw error;
  }
}
function check(condition, message) {
  if (!condition) throw new Error(message);
}
const one = (rows, what) => {
  check(Array.isArray(rows) && rows.length === 1, `expected exactly one ${what}, found ${rows?.length ?? 0}`);
  return rows[0];
};

// ── Test customers (fictional; deleted at the end) ───────────────────────────
const run = `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`;
const customer = (n, name, country, timezone) => ({ name, country, timezone, email: `nfo-e2e-${run}-${n}@${DOMAIN}`, password: `E2e-${randomUUID()}` });
const c1 = customer(1, "Asha Example", "AE", "Asia/Dubai");
const c2 = customer(2, "Bala Example", "GB", "Europe/London");

async function profileOf(c) {
  const { data, error } = await admin.from("profiles").select("*").eq("email", c.email).maybeSingle();
  if (error) throw new Error(`admin read of profiles failed: ${error.message}`);
  return data;
}

// ── Browser ──────────────────────────────────────────────────────────────────
const engines = { chromium, firefox, webkit };
const launchOptions = { headless: process.env.E2E_HEADED !== "true" };
const browser = engines[CHANNEL] ? await engines[CHANNEL].launch(launchOptions) : await chromium.launch({ ...launchOptions, channel: CHANNEL });
const pageErrors = [];

async function newCustomerPage(label, timezoneId) {
  const context = await browser.newContext({
    viewport: { width: 1280, height: 900 },
    // The registration form takes the time zone from the browser.
    timezoneId,
    // A distinct client address per customer keeps the app's rate limits per person.
    extraHTTPHeaders: { "x-forwarded-for": `198.51.100.${Math.floor(Math.random() * 250) + 1}` },
  });
  const page = await context.newPage();
  // WebKit reports RSC prefetches cancelled by the next navigation as "access
  // control" errors (as in scripts/qa.mjs). They never reach users.
  const ignored = (message) => CHANNEL === "webkit" && /_rsc=.*access control checks/.test(message);
  page.on("pageerror", (error) => {
    if (!ignored(error.message)) pageErrors.push(`${label}: ${error.message}`);
  });
  page.on("console", (msg) => {
    if (msg.type() === "error" && !ignored(msg.text())) pageErrors.push(`${label}: console: ${msg.text()}`);
  });
  return { context, page };
}

// Portal pages stream in after a loading skeleton (which has no <h1>).
const ready = (page) => page.locator("main h1").first().waitFor({ timeout: 20_000 });
const heading = async (page) => (await ready(page), page.locator("main h1").first().textContent());
const text = async (page) => (await ready(page), page.locator("main").textContent());
const path = (page) => new URL(page.url()).pathname;

async function signIn(page, c) {
  await page.goto(`${BASE}/login`);
  await page.locator("#email").fill(c.email);
  await page.locator("#password").fill(c.password);
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await page.waitForURL(`${BASE}/app`, { timeout: 20_000 });
}

async function signOut(page) {
  await page.getByRole("button", { name: "Sign out" }).first().click();
  await page.waitForURL(`${BASE}/login?notice=signed-out`, { timeout: 20_000 });
}

/**
 * Opens `url` and expects the portal's "not found" answer, identical for a
 * missing record and someone else's. Pages stream behind a loading state, so
 * this is a "soft" 404: status 200 with a noindex tag (see Next's loading.js
 * docs); a hard 404 is accepted too.
 */
async function expectNoAccess(page, url, body) {
  const response = await page.goto(url);
  check([200, 404].includes(response?.status() ?? 0), `${url} answered ${response?.status()}`);
  const content = await text(page);
  check(content.includes(body), `${url} did not show "${body}"`);
  const robots = await page.locator('meta[name="robots"]').evaluateAll((tags) => tags.map((t) => t.getAttribute("content")).join(" "));
  check(robots.includes("noindex"), `${url} is not marked noindex`);
  return content;
}

console.log(`Portal acceptance test against ${BASE} (${CHANNEL}), project ${new URL(SUPABASE_URL).host}\n`);

const ids = {};
const session1 = await newCustomerPage("customer 1", c1.timezone);
const session2 = await newCustomerPage("customer 2", c2.timezone);
let exitCode = 0;

try {
  const page = session1.page;

  await step("1. Create a new customer account (the real registration form)", async () => {
    await page.goto(`${BASE}/register`);
    check(await page.locator("#fullName").isVisible(), "the registration form is not shown — is the app started with CUSTOMER_SIGNUPS_OPEN=true and the Supabase env vars?");
    await page.locator("#fullName").fill(c1.name);
    await page.locator("#email").fill(c1.email);
    await page.locator("#password").fill(c1.password);
    await page.locator("#country").selectOption(c1.country);
    await page.locator("#consent").check();
    await page.getByRole("button", { name: "Create account" }).click();
    const outcome = await Promise.race([
      page.waitForURL(`${BASE}/app`, { timeout: 30_000 }).then(() => "workspace"),
      page.getByText("We've sent a confirmation link").waitFor({ timeout: 30_000 }).then(() => "email"),
      page
        .locator('[role="alert"] p')
        .first()
        .waitFor({ timeout: 30_000 })
        .then(async () => `error: ${await page.locator('[role="alert"] p').first().textContent()}`),
    ]);
    if (outcome === "email") {
      // Confirmation is on: finish through a real confirmation link, without sending email.
      const { data, error } = await admin.auth.admin.generateLink({ type: "signup", email: c1.email, password: c1.password });
      check(!error, `could not generate a confirmation link: ${error?.message}`);
      await page.goto(`${BASE}/auth/confirm?token_hash=${data.properties.hashed_token}&type=signup&next=%2Fapp`);
      await page.waitForURL(`${BASE}/app`, { timeout: 20_000 });
    } else if (/can't send email|different email address/.test(outcome)) {
      // The form reached Supabase, but the project can't email test addresses yet (its built-in
      // email only reaches your own team). Create the same account through the admin API and
      // confirm it with a real email link, so the rest of the journey still runs.
      console.log(`      note: Supabase refused to email the test address ("${outcome.replace(/^error: /, "")}"); confirming the account through an admin-generated link instead.`);
      const { data, error } = await admin.auth.admin.generateLink({
        type: "signup",
        email: c1.email,
        password: c1.password,
        options: { data: { full_name: c1.name, country: c1.country, timezone: c1.timezone } },
      });
      check(!error, `could not create the account through the admin API: ${error?.message}`);
      await page.goto(`${BASE}/auth/confirm?token_hash=${data.properties.hashed_token}&type=signup&next=%2Fapp`);
      await page.waitForURL(`${BASE}/app`, { timeout: 20_000 });
    } else check(outcome === "workspace", `registration failed: ${outcome}`);

    const profile = await profileOf(c1);
    check(profile, "no profile was created for the new account");
    check(profile.role === "CUSTOMER", `new account has role ${profile.role}`);
    check(profile.full_name === c1.name && profile.country === c1.country && profile.timezone === c1.timezone, "profile details were not copied from the form");
    ids.c1Profile = profile.id;
    ids.c1Auth = profile.auth_user_id;
  });

  await step("2. Login", async () => {
    await session1.context.clearCookies();
    const response = await page.goto(`${BASE}/app`);
    check(path(page) === "/login", `signed-out /app ended on ${page.url()} (status ${response?.status()})`);
    await signIn(page, c1);
    // The session lives only in HttpOnly cookies: page scripts can never read the tokens.
    const sessionCookies = (await session1.context.cookies()).filter((cookie) => cookie.name.startsWith("sb-"));
    check(sessionCookies.length > 0, "no session cookie was set");
    check(sessionCookies.every((cookie) => cookie.httpOnly), "session cookies are not HttpOnly");
    // Playwright's WebKit on Windows does not implement SameSite (it reports "None" even though
    // the server sends SameSite=Lax), so that part is checked in Chromium and Firefox.
    if (CHANNEL !== "webkit") check(sessionCookies.every((cookie) => cookie.sameSite === "Lax"), "session cookies are not SameSite=Lax");
    check(!(await page.evaluate(() => document.cookie)).includes("sb-"), "page scripts can read the session cookie");
  });

  await step("3. Arrive at an empty dashboard", async () => {
    const content = await text(page);
    check((await heading(page)).includes("Asha"), "dashboard greeting does not use the customer's first name");
    for (const expected of ["Set up your workspace", "No properties yet", "Nothing needs your attention"]) check(content.includes(expected), `dashboard is missing "${expected}"`);
    check(!/REQ-\d/.test(content), "a new dashboard shows a request number");
  });

  await step('4. Add "Chennai House"', async () => {
    await page.getByRole("link", { name: "Add property" }).first().click();
    await page.waitForURL(`${BASE}/app/properties/new`);
    await page.locator("#name").fill("Chennai House");
    await page.locator("#propertyType").selectOption("HOUSE");
    await page.locator("#city").fill("Chennai");
    await page.locator("#district").selectOption("Chennai");
    await page.locator("#postalCode").fill("600020");
    await page.getByRole("button", { name: "Add property" }).click();
    await page.waitForURL(/\/app\/properties\/[0-9a-f-]{36}\?saved=created$/, { timeout: 20_000 });
    ids.property = path(page).split("/").pop();
    const { data } = await admin.from("properties").select("owner_id, name, city, postal_code, state").eq("id", ids.property);
    const row = one(data, "property row");
    check(row.owner_id === ids.c1Profile, "the property is not owned by customer 1");
    check(row.name === "Chennai House" && row.postal_code === "600020" && row.state === "Tamil Nadu", "property fields were not saved as entered");
  });

  await step("5. It appears on the dashboard", async () => {
    await page.goto(`${BASE}/app`);
    await page.getByRole("region", { name: "My properties" }).getByRole("link", { name: /Chennai House/ }).waitFor();
  });

  await step("6. Open the property", async () => {
    await page.getByRole("region", { name: "My properties" }).getByRole("link", { name: /Chennai House/ }).click();
    await page.waitForURL(`${BASE}/app/properties/${ids.property}`);
    await page.locator("main h1", { hasText: "Chennai House" }).waitFor({ timeout: 20_000 });
  });

  await step('7. Create "Garden Maintenance"', async () => {
    await page.locator(`main a[href="/app/requests/new?property=${ids.property}"]`).first().click();
    await page.waitForURL(`${BASE}/app/requests/new?property=${ids.property}`);
    check(await page.locator(`input[name="propertyId"][value="${ids.property}"]`).isChecked(), "Chennai House is not preselected");
    await page.locator('input[name="category"][value="GARDEN_MAINTENANCE"]').check();
    await page.locator("#title").fill("Garden Maintenance");
    await page.locator("#description").fill("Please trim the hedges, clear the fallen leaves and water the plants.");
    await page.getByRole("button", { name: "Review request" }).click();
    const review = page.getByRole("region", { name: "Review your request" });
    await review.waitFor();
    const summary = await review.textContent();
    check(summary.includes("Chennai House, Chennai") && summary.includes("Garden Maintenance"), "the review does not show the property and summary");
  });

  await step("8. Submit the request", async () => {
    await page.getByRole("button", { name: "Submit request" }).click();
    await page.waitForURL(/\/app\/requests\/[0-9a-f-]{36}\?saved=created$/, { timeout: 20_000 });
    ids.request = path(page).split("/").pop();
  });

  await step("9. A REQ-XXXXXX number is created", async () => {
    const eyebrow = await page.locator("main").getByText(/^Service request · REQ-\d{6}$/).textContent();
    ids.requestNumber = eyebrow.split("· ")[1];
    const { data } = await admin.from("service_requests").select("request_number, customer_id, property_id, title, category, priority").eq("id", ids.request);
    const row = one(data, "request row");
    check(row.request_number === ids.requestNumber, `page shows ${ids.requestNumber}, database has ${row.request_number}`);
    check(row.customer_id === ids.c1Profile && row.property_id === ids.property, "request is not linked to customer 1 and Chennai House");
    check(row.title === "Garden Maintenance" && row.category === "GARDEN_MAINTENANCE" && row.priority === "NORMAL", "request fields were not saved as entered");
  });

  await step("10. Status is SUBMITTED", async () => {
    const { data } = await admin.from("service_requests").select("status").eq("id", ids.request);
    check(one(data, "request row").status === "SUBMITTED", "database status is not SUBMITTED");
    await page.locator("main").getByText("Submitted", { exact: true }).first().waitFor();
  });

  await step('11. The timeline contains "Request submitted"', async () => {
    const timeline = await page.getByRole("list", { name: "What has happened" }).textContent();
    check(timeline.includes("Request submitted"), "timeline has no 'Request submitted'");
    const { data } = await admin.from("service_request_events").select("title, visibility, event_type").eq("request_id", ids.request);
    const event = one(data, "request event");
    check(event.title === "Request submitted" && event.visibility === "CUSTOMER", "the stored event is not a customer-visible 'Request submitted'");
  });

  await step('12. Activity contains "Service request created"', async () => {
    await page.goto(`${BASE}/app/activity`);
    const content = await text(page);
    check(content.includes("Service request created") && content.includes(ids.requestNumber), "activity page has no 'Service request created' entry for the request");
    const { data } = await admin.from("activity_logs").select("action, actor_id").eq("customer_id", ids.c1Profile).eq("entity_id", ids.request);
    const entry = one(data, "activity entry for the request");
    check(entry.action === "REQUEST_CREATED" && entry.actor_id === ids.c1Profile, "activity entry is not REQUEST_CREATED by customer 1");
  });

  await step('13. Notification exists: "Your service request has been received."', async () => {
    await page.goto(`${BASE}/app/notifications`);
    const unread = await page.getByRole("region", { name: /^Unread/ }).textContent();
    check(unread.includes("Your service request has been received."), "notification not listed under Unread");
    const { data } = await admin.from("notifications").select("title, read_at").eq("user_id", ids.c1Profile).eq("entity_id", ids.request);
    const notification = one(data, "notification for the request");
    check(notification.read_at === null, "the new notification is already marked read");
    ids.notificationCount = 1;
  });

  await step("14. Logout", async () => {
    await signOut(page);
    await page.goto(`${BASE}/app/requests/${ids.request}`);
    check(path(page) === "/login", "after signing out, the request page is still reachable");
  });

  const page2 = session2.page;
  await step("15. Create a second customer (confirmed through an email link)", async () => {
    const { data, error } = await admin.auth.admin.generateLink({
      type: "signup",
      email: c2.email,
      password: c2.password,
      options: { data: { full_name: c2.name, country: c2.country, timezone: c2.timezone } },
    });
    check(!error, `could not create the second account: ${error?.message}`);
    const link = `${BASE}/auth/confirm?token_hash=${data.properties.hashed_token}&type=signup&next=%2Fapp`;
    await page2.goto(link);
    await page2.waitForURL(`${BASE}/app`, { timeout: 20_000 });
    check((await heading(page2)).includes("Bala"), "second customer is not signed in to their own workspace");
    const profile = await profileOf(c2);
    ids.c2Profile = profile.id;
    ids.c2Auth = profile.auth_user_id;
    // Email links work once.
    const reused = await browser.newContext();
    const reusedPage = await reused.newPage();
    await reusedPage.goto(link);
    check(new URL(reusedPage.url()).search.includes("link-expired"), "a used confirmation link worked a second time");
    await reused.close();
  });

  await step("16. The second customer cannot reach any of customer 1's data", async () => {
    // Through the app…
    await expectNoAccess(page2, `${BASE}/app/properties/${ids.property}`, "This property may have been removed or you may not have access to it.");
    await expectNoAccess(page2, `${BASE}/app/properties/${ids.property}/edit`, "This property may have been removed or you may not have access to it.");
    const requestPage = await expectNoAccess(page2, `${BASE}/app/requests/${ids.request}`, "This request may have been removed or you may not have access to it.");
    check(!requestPage.includes(ids.requestNumber), "the request number leaked onto the not-found page");
    for (const route of ["/app", "/app/properties", "/app/requests", "/app/activity", "/app/notifications"]) {
      await page2.goto(`${BASE}${route}`);
      const content = await text(page2);
      for (const secret of ["Chennai House", ids.requestNumber, "Garden Maintenance", "Your service request has been received.", "Asha"]) {
        check(!content.includes(secret), `${route} shows customer 1's "${secret}" to customer 2`);
      }
    }

    // …a forged form (someone else's property id submitted to the request action)…
    await page2.goto(`${BASE}/app/requests/new?property=${ids.property}`);
    await ready(page2);
    check((await page2.locator(`input[name="propertyId"][value="${ids.property}"]`).count()) === 0, "customer 1's property is offered to customer 2");
    await page2.locator('input[name="category"][value="MAINTENANCE"]').check();
    await page2.locator("#description").fill("Trying to file a request on someone else's property.");
    await page2.getByRole("button", { name: "Review request" }).click();
    await page2.getByRole("region", { name: "Review your request" }).waitFor();
    // Forge the value after React's last render (React re-applies `value` on every render).
    await page2.evaluate((foreignId) => {
      const radio = document.querySelector('input[name="propertyId"]');
      radio.value = foreignId;
      radio.checked = true;
    }, ids.property);
    await page2.getByRole("button", { name: "Submit request" }).click();
    await page2.getByText("Please choose one of your properties.").waitFor({ timeout: 20_000 });
    check(path(page2) === "/app/requests/new", "the forged request was accepted");
    const { data: c2Requests } = await admin.from("service_requests").select("id").eq("customer_id", ids.c2Profile);
    check(c2Requests.length === 0, "a request was created from the forged form");

    // …and straight at the database API, signed in as customer 2 with the public key.
    const asC2 = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, noSession);
    const { error: signInError } = await asC2.auth.signInWithPassword({ email: c2.email, password: c2.password });
    check(!signInError, `direct sign-in as customer 2 failed: ${signInError?.message}`);
    const reads = {
      property: await asC2.from("properties").select("id").eq("id", ids.property),
      request: await asC2.from("service_requests").select("id").eq("id", ids.request),
      events: await asC2.from("service_request_events").select("id").eq("request_id", ids.request),
      activity: await asC2.from("activity_logs").select("id").eq("customer_id", ids.c1Profile),
      notifications: await asC2.from("notifications").select("id").eq("user_id", ids.c1Profile),
      profile: await asC2.from("profiles").select("id").eq("id", ids.c1Profile),
    };
    for (const [what, { data, error }] of Object.entries(reads)) check(!error && data.length === 0, `customer 2 can read customer 1's ${what}`);
    const writes = {
      "rename the property": await asC2.from("properties").update({ name: "Taken" }).eq("id", ids.property).select("id"),
      "cancel the request": await asC2.from("service_requests").update({ status: "CANCELLED" }).eq("id", ids.request).select("id"),
      "mark the notification read": await asC2.from("notifications").update({ read_at: new Date().toISOString() }).eq("user_id", ids.c1Profile).select("id"),
      "delete the property": await asC2.from("properties").delete().eq("id", ids.property).select("id"),
    };
    for (const [what, { data, error }] of Object.entries(writes)) check(error || data.length === 0, `customer 2 could ${what}`);
    const insert = await asC2
      .from("service_requests")
      .insert({ property_id: ids.property, category: "OTHER", title: "Injected", description: "Injected through the API.", priority: "NORMAL" })
      .select("id");
    check(insert.error, "customer 2 could create a request on customer 1's property");
    const promote = await asC2.from("profiles").update({ role: "ADMIN" }).eq("id", ids.c2Profile).select("id");
    check(promote.error || promote.data.length === 0, "customer 2 could change their own role");
    await asC2.auth.signOut({ scope: "local" });
    await signOut(page2);
  });

  await step("17. Return to customer 1", async () => {
    await signIn(page, c1);
  });

  await step("18. All of customer 1's data is intact", async () => {
    const dashboard = await text(page);
    check(dashboard.includes("Chennai House") && dashboard.includes(ids.requestNumber), "dashboard lost the property or the request");
    await page.goto(`${BASE}/app/requests/${ids.request}`);
    const requestPage = await text(page);
    check(requestPage.includes(ids.requestNumber) && requestPage.includes("Garden Maintenance") && requestPage.includes("Submitted"), "request page changed");
    check((await page.getByRole("list", { name: "What has happened" }).textContent()).includes("Request submitted"), "timeline changed");
    await page.goto(`${BASE}/app/activity`);
    check((await text(page)).includes("Service request created"), "activity entry is gone");
    await page.goto(`${BASE}/app/notifications`);
    check((await page.getByRole("region", { name: /^Unread/ }).textContent()).includes("Your service request has been received."), "notification is gone or was marked read");

    const [property, request, events, notifications, requestsOnProperty] = await Promise.all([
      admin.from("properties").select("name, owner_id").eq("id", ids.property),
      admin.from("service_requests").select("status, title, customer_id").eq("id", ids.request),
      admin.from("service_request_events").select("id").eq("request_id", ids.request),
      admin.from("notifications").select("read_at").eq("user_id", ids.c1Profile),
      admin.from("service_requests").select("id").eq("property_id", ids.property),
    ]);
    const p = one(property.data, "property row");
    const r = one(request.data, "request row");
    check(p.name === "Chennai House" && p.owner_id === ids.c1Profile, "property row changed");
    check(r.status === "SUBMITTED" && r.title === "Garden Maintenance" && r.customer_id === ids.c1Profile, "request row changed");
    one(events.data, "request event");
    check(one(notifications.data, "notification").read_at === null, "notification row changed");
    one(requestsOnProperty.data, "request on Chennai House (no injected requests)");
  });

  // ── Beyond the checklist: the rest of the everyday flows ─────────────────
  await step("Mark the notification as read", async () => {
    await page.getByRole("button", { name: "Mark as read" }).first().click();
    await page.getByRole("region", { name: "Read", exact: true }).getByText("Your service request has been received.").waitFor({ timeout: 20_000 });
    const { data } = await admin.from("notifications").select("read_at").eq("user_id", ids.c1Profile);
    check(one(data, "notification").read_at !== null, "read_at was not set");
  });

  await step("Update the profile (logged as PROFILE_UPDATED, email read-only)", async () => {
    await page.goto(`${BASE}/app/profile`);
    check(await page.locator("#email").evaluate((el) => el.readOnly), "email is editable");
    await page.locator("#phone").fill("+971 50 000 0000");
    await page.getByRole("button", { name: "Save profile" }).click();
    await page.getByText("Your profile has been saved.").waitFor({ timeout: 20_000 });
    const { data } = await admin.from("activity_logs").select("metadata").eq("customer_id", ids.c1Profile).eq("action", "PROFILE_UPDATED");
    check(one(data, "PROFILE_UPDATED entry").metadata?.fields?.includes("phone"), "PROFILE_UPDATED does not name the changed field");
  });

  await step("Reset the password through a recovery link", async () => {
    await signOut(page);
    const { data, error } = await admin.auth.admin.generateLink({ type: "recovery", email: c1.email });
    check(!error, `could not generate a recovery link: ${error?.message}`);
    await page.goto(`${BASE}/auth/confirm?token_hash=${data.properties.hashed_token}&type=recovery&next=%2Freset-password`);
    await page.waitForURL(`${BASE}/reset-password`, { timeout: 20_000 });
    const oldPassword = c1.password;
    c1.password = `E2e-${randomUUID()}`;
    await page.locator("#password").fill(c1.password);
    await page.locator("#confirmPassword").fill(c1.password);
    await page.getByRole("button", { name: "Set new password" }).click();
    await page.waitForURL(`${BASE}/app?saved=password`, { timeout: 20_000 });
    await signOut(page);
    await page.locator("#email").fill(c1.email);
    await page.locator("#password").fill(oldPassword);
    await page.getByRole("button", { name: "Sign in", exact: true }).click();
    await page.getByText("The email or password is incorrect.").waitFor({ timeout: 20_000 });
    await signIn(page, c1);
  });

  await step("Cancel the request (a real status change on the timeline)", async () => {
    await page.goto(`${BASE}/app/requests/${ids.request}`);
    await page.getByRole("button", { name: "Cancel request" }).first().click();
    await page.getByRole("dialog").getByRole("button", { name: "Cancel request" }).click();
    await page.waitForURL(`${BASE}/app/requests/${ids.request}?saved=cancelled`, { timeout: 20_000 });
    const { data } = await admin.from("service_request_events").select("event_type").eq("request_id", ids.request);
    check(data.length === 2, `expected 2 timeline events after cancelling, found ${data.length}`);
    check((await text(page)).includes("Cancelled"), "the page does not show the cancelled status");
  });

  if (pageErrors.length) {
    console.log(`\nBrowser errors:\n${pageErrors.map((e) => `  ✗ ${e}`).join("\n")}`);
    exitCode = 1;
  }
} catch {
  exitCode = 1;
} finally {
  await browser.close();
  if (KEEP) console.log(`\nKept the test accounts: ${c1.email}, ${c2.email}`);
  else {
    for (const c of [c1, c2]) {
      const profile = await profileOf(c).catch(() => null);
      if (!profile) continue;
      const { error } = await admin.auth.admin.deleteUser(profile.auth_user_id);
      if (error) {
        console.log(`  ! could not delete ${c.email}: ${error.message}`);
        exitCode = 1;
      } else if (await profileOf(c)) {
        console.log(`  ! ${c.email} was deleted but its profile remains`);
        exitCode = 1;
      }
    }
    console.log("\nDeleted the test accounts (their properties, requests, activity and notifications go with them).");
  }
}

const passed = results.filter((r) => r.ok).length;
console.log(`\n${passed}/${results.length} steps passed.`);
if (exitCode === 0) console.log("✓ Portal acceptance test passed");
process.exit(exitCode);
